[server]
host = f2b.yxliuchn.uk
port = 443
protocol = https

[logging]
log_file = client.log
max_bytes = 1048576
backup_count = 3

[fail2ban]
# 支持多个jail，用逗号分隔
jails = sshd,invalid-user

[auth]
token = ADD_YOUR_TOKEN
